### ISSUE TITLE
Suggestion: change the title slightly

### ISSUE THREAD

**Issue by cjforms** [vickytnz/accessibility-examples#7]
The current title is "Common form accessibility mistakes" which is quite a hefty noun string.

In the explanation, you call it "Common accessibility mistakes in forms" which is a little easier to parse. 

Suggestion: change the title accordingly.

(Side note: if you're going with "common accessibility mistakes in forms"  then check that it's always 'in forms' not accidentally 'on forms' in some places)

**Comment by vickytnz** [comment]
Changed and pushed to next update
